### ISSUE TITLE
rt: panic if the `threading` feature is enabled but no threads exists 

### ISSUE THREAD

**Issue by elenaf9** [future-proof-iot/RIOT-rs#148]
If the `threading` feature is enabled but the user didn't define any threads with the `#[thread]` macro (or manually), the startup panics.

**Details**

With the feature enabled, the runtime  starts all `THREAD_FNS` (where threads are created and added to the runqueue) and then the threading itself:
https://github.com/future-proof-iot/RIOT-rs/blob/af8d78dd2c31ad95cfb11446e8d1f6bdd8ec60bc/src/riot-rs-rt/src/threading.rs#L6-L14

`start_threading` panics if there is no thread in the runqueue:
https://github.com/future-proof-iot/RIOT-rs/blob/af8d78dd2c31ad95cfb11446e8d1f6bdd8ec60bc/src/riot-rs-threads/src/lib.rs#L150-L154

Came up in https://github.com/future-proof-iot/RIOT-rs/pull/133#discussion_r1511728662. Lmk if I am missing something.

**Comment by kaspar030** [comment]
> In the `examples/threading` example, comment out both thread functions.

... and run with `--disable silent-panic`, which I didn't when testing. ;(
