### ISSUE TITLE
Schedule nightly checks in CI

### ISSUE THREAD

**Issue by ROMemories** [future-proof-iot/RIOT-rs#175]
We would benefit from running some long-running checks nightly in CI.

In particular, the CI jobs triggered on PRs only build for selected boards; it would be useful to build for every board every night using `laze --verbose build --global`.
Additionally, build failures should be reported on our Matrix channel.
Ideally, in case of failure, that scheduled CI job would also bisect the commit that introduced breakage and open an issue about it, assigning the original committer.

**Comment by kaspar030** [comment]
> Ideally, in case of failure, that scheduled CI job would also bisect the commit that introduced breakage and open an issue about it, assigning the original committer.

ah, should we keep this issue open for the bisecting part? TBH, I'd rather move this into a generic "nice to have" tracking issue.
