### ISSUE TITLE
nrf53840dk: first compilation issue

### ISSUE THREAD

**Issue by emmanuelsearch** [future-proof-iot/RIOT-rs#196]
Upon first compilation, the compiler errors and stops, complaining that:

error: can't find crate for 'core'
  |
  = note: the `thumbv8m.main-none-eabi` target may not be installed
  = help: consider downloading the target with `rustup target add thumbv8m.main-none-eabi`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

`rustup target add thumbv8m.main-none-eabi` indeed fixes it. Do we tolerate this, or is there a path to automate this rustup provisioning?

**Comment by kaspar030** [comment]
> Do we tolerate this, or is there a path to automate this rustup provisioning?

There's `laze b install-toolchain`, which is listed in the first steps. That was not installing the thumbv8 target, though ... #197.
