### ISSUE TITLE
Hardfault handler broken

### ISSUE THREAD

**Issue by thejpster** [future-proof-iot/RIOT-rs#295]
You should be aware of https://github.com/rust-embedded/cortex-m/issues/532, as you appear to have a hardfault handler that relies on the exception frame being provided. This is broken in cortex-m-rt 0.7.4.

**Comment by chrysn** [comment]
I'm not really familiar with that portion of the code, assigning to Kaspar.

As that code section has a note that it was copied from Tock: That relates to several of the register reads, but taking the xpsr from the ExceptionFrame is something that AIU was new in our version of it.

**Comment by thejpster** [comment]
The bug is that the exception frame reference is garbage in c-m-rt 0.7.4, so anything you try and read from it will cause a second fault (probably due to alignment). I think you should pin to cortex-m-rt 0.7.3 until a bugfix is released.

**Comment by kaspar030** [comment]
Thanks, confirmed. #296 pins `cortex-m-rt` to 0.7.3.

I hadn't actually seen that hard fault debug output in a while, as the `bkpt` causes probe-rs to exit before it even gets there...

**Comment by kaspar030** [comment]
Closing as we've fixed this by workaround.
