### ISSUE TITLE
community: revisit the `authors` manifest key

### ISSUE THREAD

**Issue by ROMemories** [future-proof-iot/RIOT-rs#574]
We intend to remove the [`authors` manifest key](https://doc.rust-lang.org/cargo/reference/manifest.html#the-authors-field) from our crate manifests, which is [soft-deprecated since 2021](https://github.com/rust-lang/rust/issues/83227), is [not included by `cargo new` anymore](https://github.com/rust-lang/cargo/pull/9282), and is not displayed by crate registry pages.

However, before we do that, we want to have ways of:

- Recognizing contributors
- Providing points of contact

The following ideas for these were proposed:

- Having a `CONTRIBUTORS.md` file
- Having points of contact in the `README.md`
- Having a dedicated "community" page on the yet-to-be-built website
- Having these somewhere in the documentation (may not be a good fit)

**Comment by bergzand** [comment]
For the readme:

https://contrib.rocks/preview?repo=ariel-os%2Fariel-os

<a href="https://github.com/ariel-os/ariel-os/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=ariel-os/ariel-os" />
</a>

**Comment by chrysn** [comment]
We already do have subsystems (not sure if/where written down), and the contact point for outside the project is the issue tracker, from where people either look up the relevant subsystem maintainer or can make sense of a `git praise` (an unfortunately missing default alias for `git blame`).

I think that removing authors and going with the image bar is a good step already; making subsystem maintainers (and possibly contributors) visible would be a good addition, but from my PoV we can just as well start removing the author tags already.
